CREATE TABLE events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    date         TIMESTAMP WITHOUT TIME ZONE,
    link_ava     VARCHAR(255),
    creator_id   BIGINT,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE likes_events
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    event_id BIGINT                                  NOT NULL,
    is_liked BOOLEAN,
    CONSTRAINT pk_likes_events PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    email        VARCHAR(255),
    password     VARCHAR(255),
    link_ava     VARCHAR(255),
    created_date TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_events
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    event_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_users_events PRIMARY KEY (id)
);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE likes_events
    ADD CONSTRAINT FK_LIKES_EVENTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE likes_events
    ADD CONSTRAINT FK_LIKES_EVENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_events
    ADD CONSTRAINT FK_USERS_EVENTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE users_events
    ADD CONSTRAINT FK_USERS_EVENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);